name: Build and Push Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - dev
    tags:
      - v*

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push Docker image with Release tag
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          yangclivia/kimi-free-api:latest
        platforms: linux/amd64
        build-args: TARGETPLATFORM=${{ matrix.platform }}
